CREATE TABLE COLLEGE (
 COLLEGE_ID integer NOT NULL,
 COLLEGE_NAME  varchar(30),
 COLLEGE_LOCATION varchar(20),
 CONSTRAINT COLLEGE_PRIMARY_KEY PRIMARY KEY (COLLEGE_ID));

 INSERT INTO COLLEGE VALUES (1,'SIWS','WADALA');
 INSERT INTO COLLEGE VALUES (2,'VSIT','SANGAM NAGAR');
 INSERT INTO COLLEGE VALUES (3,'VP','GANESH NAGAR');
 INSERT INTO COLLEGE VALUES (4,'K.C. COLLEGE','KURLA');

 UPDATE COLLEGE SET COLLEGE_NAME='RAJASHIVAJI' WHERE COLLEGE_ID=3;
 DELETE FROM COLLEGE WHERE COLLEGE_ID=4;
 
 select * from college;


 CREATE TABLE STUDENT (
 STUDENT_ID integer NOT NULL,
 STUDENT_ADDRESS varchar(30),
 COLLEGE_ID integer NOT NULL,
 BRANCH VARCHAR(30),
 DOB VARCHAR(30),
 CONSTRAINT STUDENT_FOREIGN_KEY FOREIGN KEY (COLLEGE_ID) REFERENCES college (COLLEGE_ID),
 CONSTRAINT STUDENT_PRIMARY_KEY PRIMARY KEY (STUDENT_ID));

 INSERT INTO STUDENT VALUES (101,'MULUND',1,'ELECTRONICS','22-09-1994');
 INSERT INTO STUDENT VALUES (102,'GOREGAON',1,'ARTS','02-02-1989');
 INSERT INTO STUDENT VALUES (103,'VIRAR',2,'SCIENCE','26-01-1999');

 select * from student;



 CREATE TABLE PROFESSOR (
 PROFESSOR_ID integer NOT NULL,
 PROFESSOR_ADDRESS varchar(30),
 COLLEGE_ID integer NOT NULL,
 BRANCH VARCHAR(30),
 DOB VARCHAR(30),
 CONSTRAINT PROFESSOR_FOREIGN_KEY FOREIGN KEY (COLLEGE_ID) REFERENCES college (COLLEGE_ID),
 CONSTRAINT PROFESSOR_PRIMARY_KEY PRIMARY KEY (PROFESSOR_ID));


 INSERT INTO PROFESSOR VALUES (1001,'PAREL',1,'IT','05-08-1975');
 INSERT INTO PROFESSOR VALUES (1002,'THANE',1,'TECH','12-01-1979');
 INSERT INTO PROFESSOR VALUES (1003,'DAHANU',2,'MECHANIC','23-04-1965');
 INSERT INTO PROFESSOR VALUES (1004,'PUNE',3,'CSS','14-04-1985');

 SELECT * FROM PROFESSOR;



 select * from college;
 select * from student;
 SELECT * FROM PROFESSOR;

DROP TABLE college;
DROP TABLE student;







